### ISSUE TITLE
Basic run question

### ISSUE THREAD

**Issue by igwill** [muhaochen/seq_ppi#11]
Hi,

I am interested in using your program to test for some cross-species PPIs in a pair of non-model organisms and have a couple very basic questions about running PIPR.

At least for a first pass, I’d like to use the multispecies. training set you provide. I see the binary interactions (.actions) named in `run.sh` and their sequences (.dictionary) named in `crnn.py`. And, I see that _yeast_wvctc_rcnn.txt is an output file from testing the yeast dataset for PPIs using the multispecies training set.
But how do I actually then bring in my own set of new protein sequences to test for possible PPIs using that training set? I don’t see a place to specify what my sequences of interest are. 
Is it line 68 of crnn.py?:
```
# ds_file, label_index, rst_file, use_emb, hidden_dim
ds_file = '../../../yest/preprocessed/Supp-AB.tsv'
```

Which is not a file I can find – is that where my data would go? What would the correct format be, something like column 1 ID - column 2 aminoacid sequence?

And a very basic question, running `python run.sh` from ‘binary/model_multi_species/’ gets me a syntax error:
```
  File "run.sh", line 1
    cd rcnn
       ^
SyntaxError: invalid syntax
```

I can edit `run.sh` to start with `python ./lasagna/crnn.py` or try to run just a single line (with a path edit to find `rcnn.py`, e.g.
`CUDA_VISIBLE_DEVICES=4 python ./lasagna/rcnn.py ../../../multi_species/preprocessed/CeleganDrosophilaEcoli.actions.tsv -1 results/all_wvctc_rcnn_25_5.txt 3 25 150
`
But I saw multiple times you explain to people just to stick to running `run.sh` and not mess with things, so I figure I must being doing something wrong haha.

Thank you!

**Comment by muhaochen** [comment]
Hi @igwill,

Sorry that I didn't realize this issue for so long until now. Perhaps you have already figured it out. But still, here are some brief answers.

> At least for a first pass, I’d like to use the multispecies. training set you provide. I see the binary interactions (.actions) named in run.sh and their sequences (.dictionary) named in crnn.py. And, I see that _yeast_wvctc_rcnn.txt is an output file from testing the yeast dataset for PPIs using the multispecies training set.
But how do I actually then bring in my own set of new protein sequences to test for possible PPIs using that training set? I don’t see a place to specify what my sequences of interest are.
Is it line 68 of crnn.py?

You see, if you run using run.sh, the ds_file should be replaced with a path to a specific file for PPI triplets. If you train the model on your own file, you need to also change id2seq_file (line 48) with your own dictionary of mapping protein ids to protein sequences (see how yeast/preprocessed/protein.dictionary.tsv is formed.).

> And a very basic question, running python run.sh from ‘binary/model_multi_species/’ gets me a syntax error

To run the sh file, you need to do bash rather than python...

Note that rcnn.py does 5-fold CV by default.

**Comment by igwill** [comment]
Thank you, I haven't had time to implement this yet - but your answers all makes sense to me!
