### ISSUE TITLE
 how to reproduce your work 

### ISSUE THREAD

**Issue by miderxi** [muhaochen/seq_ppi#9]
when i run your code i did find same code had some bugs  and same shell  seen never had been run before.
so how can you get your work done,maybe i am wrong,but that is so  confued .
so can you offer a more detail document  show your work flow and how to get this work.
by the way ,it would be better if you can offer the list file of the functions of every file in your project

**Comment by muhaochen** [comment]
![image](https://user-images.githubusercontent.com/12452252/115573909-c3d89300-a286-11eb-9d40-7a3571cdd27b.png)

What did you mean by "same code had some bugs and same shell seen never had been run before"?
I put shell scripts in each folder already for each experiment and people had executed them without issues.
I believe the decumentation is detailed enough.
"by the way ,it would be better if you can offer the list file of the functions of every file in your project" what were you even talking about?

**Comment by miderxi** [comment]
for example /type/run.sh,this nsdh file you must nerver had runed,because the default parameter is wrong,if you did you must find this quetion

**Comment by miderxi** [comment]
you may done your work well,but when you upload the code you'd better check again to make sure that all the code can run well

**Comment by miderxi** [comment]
that is what i mean

**Comment by muhaochen** [comment]
Since you come in a way to educate us authors (I am looping in the other co-first author @chelseaju so that we both can learn from you ):
Why don't you kindly start by teaching us what kind of bug(s) have you seen? Please don't simply complain with "when i run your code i did find same code had some bugs and same shell seen never had been run before. so how can you get your work done,maybe i am wrong,but that is so confued." without giving any referable information.
How would we know what issue did you face, what environment did you run on, and have you resolved that issue or not?
By saying some code has bugs without giving any specification -- did you expect us to read the entire package and test everything like your compiler did, and predict what environment you were using?
Also, if I were you, I would avoid asking much of other people's effort to solve my own problem like "offer a more detail document show your work flow and how to get this work", "offer the list file of the functions of every file" and "[why not pu add you result in your code](https://github.com/muhaochen/seq_ppi/issues/10)". You are using a free open source software. Other people's effort is usually not free and has no commitment to satisfy your own benefit of needing "a list of all functions of all files". And there is a published paper with tons of details you can read.

**Comment by miderxi** [comment]
Don't worry,I didnot find big bug problme.  
I don't mean to educate your authors. you do not have to upset  yourself.
If I were you,I would  consider it as a advice but not a educate.
And thank you that let me know other  people's effort is usually not free,this change my opinion.

**Comment by muhaochen** [comment]
Also, I tested type/run.sh again on my server and it ran without an issue. Then, what was the error you got anyway?

**Comment by miderxi** [comment]
a file name problem,after i rename name parameter,I run into other problem,so i just stop

➜  seq_ppi git:(master) sh type/model/run.sh 
type/model/run.sh: 1: cd: can't cd to lasagna
python: can't open file 'rcnn.py': [Errno 2] No such file or directory
python: can't open file 'rcnn.py': [Errno 2] No such file or directory
python: can't open file 'rcnn.py': [Errno 2] No such file or directory
python: can't open file 'rcnn.py': [Errno 2] No such file or directory

**Comment by muhaochen** [comment]
![image](https://user-images.githubusercontent.com/12452252/115949737-a4b34e80-a49c-11eb-847b-63318895aef3.png)


> Don't worry,I didnot find big bug problme.
> I don't mean to educate your authors. you do not have to upset yourself.
> If I were you,I would consider it as a advice but not a educate.
> And thank you that let me know other people's effort is usually not free,this change my opinion.

Sure. Whatever you meant to do. Where did you come with the presumption about "we must have never run our script", despite of the fact that we HAVE actually done so?

![image](https://user-images.githubusercontent.com/12452252/115949920-c3feab80-a49d-11eb-9c8b-b7d05a579d3d.png)

You call that a bug of code??? Learn how to cd and how to change file directories by yourself. Frankly, letting people look at such basic stuffs for you is a total waste of time (and is insulting). This conversation is over.

**Comment by miderxi** [comment]
you win
